
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider"

import './globals.css'
import { CrispProvider } from '@/components/crisp-provider'
import { ModalProvider } from '@/components/modal-provider'
import { ToasterProvider } from '@/components/toaster-provide'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = 'force-dynamic'; // Add this line


export const metadata: Metadata = {
  title: 'GPTOCR',
  description: 'Generated by Dyanesh',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <CrispProvider/>
      <body className={inter.className}>

      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ModalProvider/>
            <ToasterProvider/>
            {children}
           
          </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>
  )
}
